### ISSUE TITLE
NaNs in few entries of nextGEMS IFS catalogs because files are not correctly read

### ISSUE THREAD

**Issue by TobiasBkr** [gribscan/gribscan#53]
Hi, 
there are occasionally some grib files in nextGEMS that are not correctly indexed by gribscan. For example in this file, only the first 14 (out of 24) time steps are being indexed:
/scratch/b/b381679/tp_test/tp_test1file/tp_20371030.grb
index file is here:
/work/bm1235/u233156/cycle4_purged/gribscan_1h1d_2D_healpix512/indices.20371030/tp_20371030.index
However, when splitting this file into 24 files for each time step, gribscan correctly reads these files in:
/scratch/b/b381679/tp_test/tp_20371030_*.grb
index files are here:
/work/bm1235/u233156/cycle4_purged/gribscan_1h1d_2D_healpix512/indices.20371030_new/*.index

The gribscan version that I have been using is from February, with the last commit:
commit 1ed2c15ac71c1743afcc5bc47352d447bd7cb0ad 

An example for a gribscan script that I used is this one:
/work/bm1235/u233156/cycle4_purged/gribscan_1h1d_2D_healpix512/indexbuild-job_20371030_test2.sh

Thanks for your help!

**Comment by d70-t** [comment]
Hi, sorry for the delay. We've been traveling a bit.

Unfortunately, I can't see the test files you mentioned anymore.
However since the version you've mentioned, we've found a few subtle problems when scanning certain grib files. In particular, the changes 590230a and 0ac35fd might be relevant for this problem. Could you confirm if the error persists when using the recent version of gribscan?

**Comment by TobiasBkr** [comment]
Thanks a lot for the suggestion to use the newest gribscan, this indeed seems to have solved the issue. After redoing the gribscan and updating the catalogs, it looks like we are not finding any NaNs anymore.
